export interface Product {
  id: string;
  name: string;
  category: "fruits" | "vegetables" | "cooked-food";
  categoryLabel: string;
  description: string;
  longDescription: string;
  weight: string;
  price: number;
  originalPrice?: number;
  image: string;
  boxImage?: string;
  nutritionHighlights: string[];
  shelfLife: string;
  howToUse: string;
  badge?: string;
}

export const products: Product[] = [
  // FRUITS
  {
    id: "strawberry",
    name: "Freeze Dried Strawberry",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Crispy, naturally sweet strawberries retaining 97% nutrients. Perfect for snacking, smoothies & desserts.",
    longDescription: "Our premium freeze-dried strawberries are carefully selected at peak ripeness and processed using advanced freeze-drying technology to lock in flavor, color, and 97% of their original nutrients. Each piece delivers an intense burst of natural strawberry flavor with a satisfying crunch. No added sugar, no preservatives — just pure fruit goodness.",
    weight: "50g",
    price: 299,
    originalPrice: 399,
    image: "/assets/products/fruits/strawberry.png",
    boxImage: "/assets/products/fruits/strawberry-box.png",
    nutritionHighlights: ["Rich in Vitamin C", "High in Antioxidants", "Natural Fiber", "Zero Added Sugar"],
    shelfLife: "12 months",
    howToUse: "Enjoy straight from the pack, add to cereals, smoothies, yogurt, or use as a topping for desserts and cakes.",
    badge: "Bestseller",
  },
  {
    id: "mango",
    name: "Freeze Dried Mango",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Tropical Alphonso mango pieces, intensely flavorful with a light crispy texture.",
    longDescription: "Experience the king of fruits in its most convenient form. Our freeze-dried mango slices are made from premium Alphonso mangoes, capturing their rich tropical flavor and vibrant golden color. Each piece is light, crispy, and bursting with natural sweetness — a guilt-free snack that tastes like summer all year round.",
    weight: "50g",
    price: 349,
    originalPrice: 449,
    image: "/assets/products/fruits/mango.png",
    nutritionHighlights: ["Rich in Vitamin A & C", "Natural Beta-Carotene", "Digestive Enzymes", "No Preservatives"],
    shelfLife: "12 months",
    howToUse: "Snack directly, blend into smoothies, add to trail mix, or use as a natural sweetener in baking.",
    badge: "Popular",
  },
  {
    id: "kiwi",
    name: "Freeze Dried Kiwi",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Tangy and refreshing kiwi slices with a delightful crunch and vibrant green color.",
    longDescription: "Our freeze-dried kiwi slices retain the tangy-sweet flavor and stunning emerald green color of fresh kiwis. Packed with more Vitamin C than oranges, these crispy slices are a nutritional powerhouse. The unique sweet-tart flavor profile makes them irresistible for both kids and adults.",
    weight: "40g",
    price: 329,
    originalPrice: 429,
    image: "/assets/products/fruits/kiwi.png",
    boxImage: "/assets/products/fruits/kiwi-box.png",
    nutritionHighlights: ["2x Vitamin C vs Oranges", "Rich in Vitamin K", "Natural Enzymes", "Low Calorie"],
    shelfLife: "12 months",
    howToUse: "Eat as a snack, add to fruit salads, cereals, or use as a garnish for cocktails and desserts.",
  },
  {
    id: "blueberry",
    name: "Freeze Dried Blueberry",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Superfood blueberries packed with antioxidants, perfect for health-conscious snacking.",
    longDescription: "These tiny powerhouses are freeze-dried at peak freshness to preserve their incredible antioxidant content. Our blueberries deliver a concentrated burst of sweet-tart flavor with every bite. Known as a superfood, they're perfect for boosting your daily nutrition while satisfying your snack cravings.",
    weight: "40g",
    price: 399,
    originalPrice: 499,
    image: "/assets/products/fruits/blueberry.png",
    boxImage: "/assets/products/fruits/blueberry-box.png",
    nutritionHighlights: ["Highest Antioxidants", "Brain Health Support", "Rich in Vitamin K", "Anti-inflammatory"],
    shelfLife: "12 months",
    howToUse: "Add to oatmeal, yogurt, smoothie bowls, baking recipes, or enjoy as a standalone superfood snack.",
    badge: "Superfood",
  },
  {
    id: "dragon-fruit",
    name: "Freeze Dried Dragon Fruit",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Exotic pink dragon fruit with a subtle sweetness and stunning visual appeal.",
    longDescription: "Our freeze-dried dragon fruit captures the exotic beauty and delicate flavor of this tropical superfruit. The vibrant magenta color and unique spotted texture make it a visual treat, while its subtle sweetness and nutritional benefits make it a smart snacking choice. Rich in prebiotics and natural enzymes.",
    weight: "40g",
    price: 449,
    originalPrice: 549,
    image: "/assets/products/fruits/dragon-fruit-box.png",
    nutritionHighlights: ["Rich in Prebiotics", "Natural Iron Source", "Vitamin C Boost", "Gut Health Support"],
    shelfLife: "12 months",
    howToUse: "Snack directly, add to smoothie bowls for color, mix into granola, or use as a decorative food topping.",
    badge: "Exotic",
  },
  {
    id: "pineapple",
    name: "Freeze Dried Pineapple",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Sweet and tangy pineapple rings with a satisfying crunch and tropical flavor.",
    longDescription: "Transport yourself to the tropics with our freeze-dried pineapple. Each piece captures the intense sweet-tangy flavor of perfectly ripe pineapples. Rich in bromelain enzyme, these crispy tropical treats support digestion while delivering a burst of sunshine in every bite.",
    weight: "50g",
    price: 299,
    originalPrice: 399,
    image: "/assets/products/fruits/pineapple-box.png",
    nutritionHighlights: ["Bromelain Enzyme", "Vitamin C Rich", "Anti-inflammatory", "Digestive Aid"],
    shelfLife: "12 months",
    howToUse: "Enjoy as a snack, add to tropical trail mix, use in baking, or rehydrate for cooking and cocktails.",
  },
  {
    id: "jamun",
    name: "Freeze Dried Jamun",
    category: "fruits",
    categoryLabel: "Fruits",
    description: "Traditional Indian black plum with a unique sweet-astringent taste and health benefits.",
    longDescription: "Rediscover the beloved Indian jamun in a modern, convenient form. Our freeze-dried jamun preserves the distinctive deep purple color and unique sweet-astringent flavor of this traditional fruit. Known in Ayurveda for its blood sugar management properties, it's a heritage superfruit for the modern age.",
    weight: "40g",
    price: 349,
    originalPrice: 449,
    image: "/assets/products/fruits/jamun.png",
    nutritionHighlights: ["Blood Sugar Support", "Rich in Iron", "Ayurvedic Heritage", "Natural Antioxidants"],
    shelfLife: "12 months",
    howToUse: "Eat directly as a snack, add to desserts, or use in traditional Indian preparations and health drinks.",
  },
  // VEGETABLES
  {
    id: "beetroot",
    name: "Freeze Dried Beetroot",
    category: "vegetables",
    categoryLabel: "Vegetables",
    description: "Vibrant ruby-red beetroot chips packed with nitrates for energy and stamina.",
    longDescription: "Our freeze-dried beetroot retains its stunning deep ruby color and earthy-sweet flavor. Rich in natural nitrates, iron, and folate, these crispy beetroot pieces are a favorite among athletes and health enthusiasts. Use them as a nutritious snack or a versatile ingredient in your kitchen.",
    weight: "50g",
    price: 249,
    originalPrice: 349,
    image: "/assets/products/vegetables/beetroot.png",
    nutritionHighlights: ["Natural Nitrates", "Iron Rich", "Folate Source", "Stamina Booster"],
    shelfLife: "12 months",
    howToUse: "Snack directly, add to salads, blend into smoothies, or crush as a natural food coloring for recipes.",
    badge: "Energy Boost",
  },
  {
    id: "broccoli",
    name: "Freeze Dried Broccoli",
    category: "vegetables",
    categoryLabel: "Vegetables",
    description: "Nutrient-dense broccoli florets with a mild flavor, perfect for soups and meals.",
    longDescription: "Our freeze-dried broccoli florets preserve the incredible nutritional profile of fresh broccoli in a convenient, shelf-stable form. Rich in sulforaphane, vitamins K and C, and dietary fiber, these florets rehydrate beautifully for cooking or can be enjoyed as a crunchy, healthy snack.",
    weight: "50g",
    price: 229,
    originalPrice: 329,
    image: "/assets/products/vegetables/broccoli-box.png",
    nutritionHighlights: ["Sulforaphane Rich", "Vitamin K & C", "High Fiber", "Cancer-Fighting Properties"],
    shelfLife: "12 months",
    howToUse: "Rehydrate with hot water for cooking, add to soups, stir-fries, pasta, or enjoy as a crunchy snack.",
  },
  {
    id: "carrot",
    name: "Freeze Dried Carrot",
    category: "vegetables",
    categoryLabel: "Vegetables",
    description: "Sweet and crunchy carrot pieces rich in beta-carotene for eye health.",
    longDescription: "Our freeze-dried carrots capture the natural sweetness and vibrant orange color of farm-fresh carrots. Packed with beta-carotene (which converts to Vitamin A), these crunchy pieces support eye health, immunity, and skin health. A versatile ingredient for both snacking and cooking.",
    weight: "50g",
    price: 199,
    originalPrice: 299,
    image: "/assets/products/vegetables/carrot.png",
    nutritionHighlights: ["Beta-Carotene Rich", "Eye Health Support", "Vitamin A Source", "Natural Sweetness"],
    shelfLife: "12 months",
    howToUse: "Snack directly, add to soups, stews, fried rice, or rehydrate for use in salads and cooking.",
  },
  {
    id: "sweet-corn",
    name: "Freeze Dried Sweet Corn",
    category: "vegetables",
    categoryLabel: "Vegetables",
    description: "Golden sweet corn kernels with a natural buttery sweetness kids love.",
    longDescription: "Our freeze-dried sweet corn kernels deliver the satisfying pop and natural buttery sweetness of freshly harvested corn. Each golden kernel is perfectly preserved to maintain its flavor, color, and nutritional value. A family-friendly snack that's especially popular with children.",
    weight: "50g",
    price: 199,
    originalPrice: 279,
    image: "/assets/products/vegetables/sweet-corn.png",
    nutritionHighlights: ["Natural Fiber", "B Vitamins", "Lutein for Eyes", "Kid-Friendly"],
    shelfLife: "12 months",
    howToUse: "Enjoy as a crunchy snack, add to salads, soups, chaats, or rehydrate for use in cooking.",
    badge: "Kids Favorite",
  },
  {
    id: "green-peas",
    name: "Freeze Dried Green Peas",
    category: "vegetables",
    categoryLabel: "Vegetables",
    description: "Protein-rich green peas with a satisfying crunch and natural sweetness.",
    longDescription: "Our freeze-dried green peas are a protein-packed snacking revolution. Each pea delivers a satisfying crunch with a naturally sweet flavor. Rich in plant protein, fiber, and essential vitamins, they're an excellent alternative to processed snacks for the whole family.",
    weight: "50g",
    price: 179,
    originalPrice: 259,
    image: "/assets/products/vegetables/green-peas.png",
    nutritionHighlights: ["Plant Protein", "High Fiber", "Vitamin K", "Iron Source"],
    shelfLife: "12 months",
    howToUse: "Snack directly, add to trail mix, use in pulao, soups, or crush as a coating for other foods.",
  },
  // COOKED FOOD
  {
    id: "chicken-biryani",
    name: "Freeze Dried Chicken Biryani",
    category: "cooked-food",
    categoryLabel: "Cooked Food",
    description: "Authentic Hyderabadi-style chicken biryani — just add hot water for a complete meal.",
    longDescription: "Experience the royal flavors of authentic Hyderabadi chicken biryani in minutes. Our freeze-dried biryani preserves the aromatic spices, tender chicken pieces, and perfectly cooked basmati rice. Simply add hot water and wait 5 minutes for a restaurant-quality meal anywhere, anytime. Perfect for travel, camping, office, or emergency food supply.",
    weight: "100g",
    price: 299,
    originalPrice: 399,
    image: "/assets/products/cooked-food/chicken-biryani.png",
    nutritionHighlights: ["Complete Meal", "High Protein", "Authentic Spices", "No Preservatives"],
    shelfLife: "24 months",
    howToUse: "Open the pack, add 150ml hot water, close and wait 5 minutes. Stir gently and enjoy your meal!",
    badge: "Bestseller",
  },
  {
    id: "prawn-biryani",
    name: "Freeze Dried Prawn Biryani",
    category: "cooked-food",
    categoryLabel: "Cooked Food",
    description: "Coastal-style prawn biryani with aromatic spices — ready in just 5 minutes.",
    longDescription: "Savor the coastal flavors of prawn biryani without the hassle of cooking. Our freeze-dried version captures the essence of fresh prawns, fragrant basmati rice, and a blend of traditional spices. Each pack delivers a complete, satisfying meal that's perfect for seafood lovers on the go.",
    weight: "100g",
    price: 349,
    originalPrice: 449,
    image: "/assets/products/cooked-food/prawn-biryani.png",
    nutritionHighlights: ["Omega-3 Fatty Acids", "High Protein", "Complete Meal", "Authentic Coastal Recipe"],
    shelfLife: "24 months",
    howToUse: "Open the pack, add 150ml hot water, close and wait 5 minutes. Stir gently and enjoy!",
    badge: "Premium",
  },
  {
    id: "chole-bhatura",
    name: "Freeze Dried Chole Bhatura",
    category: "cooked-food",
    categoryLabel: "Cooked Food",
    description: "North Indian classic chole bhatura — rich, spicy chickpea curry ready in minutes.",
    longDescription: "Enjoy the beloved North Indian street food classic anywhere in the world. Our freeze-dried chole bhatura features rich, spicy chickpea curry with authentic Punjabi flavors. The perfectly balanced blend of spices creates a hearty, satisfying meal that tastes just like homemade.",
    weight: "80g",
    price: 249,
    originalPrice: 349,
    image: "/assets/products/cooked-food/chole-bhatura.png",
    nutritionHighlights: ["Plant Protein", "High Fiber", "Iron Rich", "Traditional Recipe"],
    shelfLife: "24 months",
    howToUse: "Add 120ml hot water to the pack, wait 5 minutes, stir well. Serve with bread or rice.",
  },
  {
    id: "dal-makhni",
    name: "Freeze Dried Dal Makhni",
    category: "cooked-food",
    categoryLabel: "Cooked Food",
    description: "Creamy, buttery dal makhni with slow-cooked flavors — comfort food made instant.",
    longDescription: "Our freeze-dried dal makhni captures the rich, creamy essence of this beloved Punjabi classic. Made with black lentils and kidney beans slow-cooked with butter and cream, then freeze-dried to perfection. Each serving delivers the authentic restaurant-quality taste of dal makhni in just 5 minutes.",
    weight: "80g",
    price: 229,
    originalPrice: 329,
    image: "/assets/products/cooked-food/dal-makhni.png",
    nutritionHighlights: ["Plant Protein", "Creamy & Rich", "Slow-Cooked Flavor", "Comfort Food"],
    shelfLife: "24 months",
    howToUse: "Add 120ml hot water, wait 5 minutes, stir well. Best enjoyed with rice, roti, or naan.",
    badge: "Comfort Food",
  },
  {
    id: "palak-paneer",
    name: "Freeze Dried Palak Paneer",
    category: "cooked-food",
    categoryLabel: "Cooked Food",
    description: "Creamy spinach and cottage cheese curry — a nutritious vegetarian delight.",
    longDescription: "Our freeze-dried palak paneer combines the goodness of fresh spinach with soft paneer cubes in a creamy, mildly spiced gravy. This vegetarian favorite is packed with iron, calcium, and protein. Simply add hot water for a wholesome, restaurant-quality meal that's both nutritious and delicious.",
    weight: "80g",
    price: 249,
    originalPrice: 349,
    image: "/assets/products/cooked-food/palak-paneer.png",
    nutritionHighlights: ["Iron & Calcium", "High Protein", "Vegetarian", "Spinach Superfood"],
    shelfLife: "24 months",
    howToUse: "Add 120ml hot water, wait 5 minutes, stir gently. Serve with rice, roti, or naan.",
  },
  {
    id: "pav-bhaji",
    name: "Freeze Dried Pav Bhaji",
    category: "cooked-food",
    categoryLabel: "Cooked Food",
    description: "Mumbai's iconic street food — spicy mixed vegetable curry ready in minutes.",
    longDescription: "Bring the taste of Mumbai streets to your table with our freeze-dried pav bhaji. This iconic dish features a rich, buttery blend of mashed vegetables with aromatic pav bhaji masala. Each pack delivers the authentic street-food experience with the convenience of instant preparation.",
    weight: "80g",
    price: 229,
    originalPrice: 329,
    image: "/assets/products/cooked-food/pav-bhaji.png",
    nutritionHighlights: ["Mixed Vegetables", "Rich in Fiber", "Mumbai Street Food", "Buttery Flavor"],
    shelfLife: "24 months",
    howToUse: "Add 100ml hot water, wait 5 minutes, stir well. Serve with buttered pav or bread.",
  },
];

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);

export const categories = [
  {
    id: "fruits",
    name: "Freeze Dried Fruits",
    description: "Crispy, naturally sweet fruits with 97% nutrients retained",
    color: "from-green-500 to-emerald-600",
    bgColor: "bg-green-50",
    textColor: "text-green-700",
    count: products.filter((p) => p.category === "fruits").length,
  },
  {
    id: "vegetables",
    name: "Freeze Dried Vegetables",
    description: "Nutrient-dense veggies perfect for cooking and snacking",
    color: "from-orange-500 to-amber-600",
    bgColor: "bg-orange-50",
    textColor: "text-orange-700",
    count: products.filter((p) => p.category === "vegetables").length,
  },
  {
    id: "cooked-food",
    name: "Freeze Dried Cooked Food",
    description: "Complete meals ready in 5 minutes — just add hot water",
    color: "from-red-500 to-rose-600",
    bgColor: "bg-red-50",
    textColor: "text-red-700",
    count: products.filter((p) => p.category === "cooked-food").length,
  },
];