"""auto update

Revision ID: 008b28c2478c
Revises: 169469bd49e3
Create Date: 2026-03-01 18:35:30.310482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '008b28c2478c'
down_revision: Union[str, Sequence[str], None] = '169469bd49e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
    op.alter_column('order_items', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('order_items', 'created_at')
    op.drop_column('order_items', 'total_price')
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'total')
    op.alter_column('products', 'category_label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'weight',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'nutrition_highlights',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'shelf_life',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'how_to_use',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('products', 'how_to_use',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'shelf_life',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'nutrition_highlights',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'weight',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category_label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('orders', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('stripe_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('orders', 'total_amount')
    op.add_column('order_items', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('order_items', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    op.drop_table('testimonials')
    # ### end Alembic commands ###